### ISSUE TITLE
Add ng-bullet as an internal to speed up TestBeds

### ISSUE THREAD

**Issue by DennisJaamann** [getsaf/shallow-render#101]
This is more a question than it is an issue.

However, when having for example an nx monorepo with 5000+ tests (or more), it becomes apparent that even when using jest as a test runner, there is a significant performance bottleneck introduced by using Angular testbeds.

https://www.npmjs.com/package/ng-bullet offers a pretty clean solution to this problem, and I was just wondering how and if this could fit in the architecture of shallow-render as well. 

Since it could considerably improve performance on large test suites especially, maybe considering adding this might be worth while.

After a quick review, it **should** only impact the renderer.js

WDYT

**Comment by getsaf** [comment]
This is very interesting...  The shallow renderer creates a dynamic component each time, I wonder if we'll still get the performance boost. I guess I'll give it a go and see how it works 🤷‍♂️

**Comment by getsaf** [comment]
I'm not sure I can make this work. The `ng-bullet` library assumes you do all of your TestBed setup in a `beforeEach` or `beforeAll`. It actually defines a `beforeAll` block automatically when you call `configureTestSuite` ([seen here](https://github.com/topnotch48/ng-bullet-workspace/blob/master/projects/ng-bullet/src/testing.ts#L22-L27)). It also assumes that the module setup is identical for every test in the `describe` block (which is something I tried to avoid with Shallow).

From my understanding of the code, it seems to convert this pattern:
```typescript
describe(() => {
  const fixture: ComponentFixture<FooComponent>;
  beforeEach(async () => {
    await TestBed.configureTestingModule({...}).compileComponents();
    fixture = TestBed.createComponent(FooComponent);
  });
});
```

to something more like this:
```typescript
describe(() => {
  const fixture: ComponentFixture<FooComponent>;
  beforeAll(async () => {
    await TestBed.configureTestingModule({...}).compileComponents();
    fixture = TestBed.createComponent(FooComponent);
  });

  afterEach(() => fixture.destroy());
  afterAll(() => TestBed.resetTestingModule());
});
```

Notice it assumes all tests have the same setup/providers/mocks, etc.

I do like the concept of "compile only once" and it may be possible to do something like this internally with Shallow. I'll keep this open while I investigate further. If you have any ideas, please feel free to post a PR or some code.

**Comment by kreatemore** [comment]
👋 I've created a prototype of some sort of caching - do we have anything we could use to benchmark the results? 

[Link to commit](https://github.com/kreatemore/shallow-render/commit/29ceb149e4e32fa6b52ef8e62dae0a58807353f8)

**Comment by getsaf** [comment]
We gave it a shot. Gonna close this issue. Will continue to keep an eye on performance enhancements as things move forward.
