### ISSUE TITLE
Jest not supported in all use cases

### ISSUE THREAD

**Issue by kylecannon** [getsaf/shallow-render#102]
Related to #99 and #100

After digging into the code in shallow-render, I found a couple of instances where there needs to be some refinements to support jest in all instances.

Here are the problem areas I've identified so far:

https://github.com/getsaf/shallow-render/blob/eab5583eaff720215ce52736cfad1fe88c8b900c/lib/models/renderer.ts#L144

https://github.com/getsaf/shallow-render/blob/7292bf9a825a5af7332653fb8ac4384f4ca99b9b/lib/tools/ng-mock.ts#L52

This isn't blocking me (yet), but a couple of spots were missed.

**Comment by getsaf** [comment]
Nice catch! I'll get a PR in for those soon.
