### ISSUE TITLE
Router test results in `Unexpected value '[object Object]' exported by the module 'MockOfErrorRoutingModule'`

### ISSUE THREAD

**Issue by jenCape** [getsaf/shallow-render#108]
I tried to follow the example [here](https://stackblitz.com/github/getsaf/shallow-render-stackblitz?file=examples%2Fcomponent-with-routing.spec.ts)

however, it doesn't work on my end, even after I simplified the component to the simplest form with `Router`:

Simplified code snippet as follows:

html:
```
<div></div>
```

component:
```
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
    selector: 'app-test',
    templateUrl: './test.component.html',
    styleUrls: ['./test.component.scss'],
})
export class TestComponent implements OnInit {
    constructor(private route: Router) {}

    ngOnInit(): void {
        console.log(this.route.url);
    }
}
```

spec:
```
import { Shallow } from 'shallow-render';

import { TestModule } from 'app/test.module';
import { TestComponent } from './test.component';

fdescribe('TestComponent', () => {
    let shallow: Shallow<TestComponent>;

    beforeEach(() => {
        shallow = new Shallow(TestComponent, TestModule);
    });

    it('should render page', async () => {
        const { find } = await shallow.render();
        expect(find('div')).toBeTruthy();
    });
});
```

i'm using `"shallow-render": "^8.0.4",` and do have the following line in `test.ts`:
```
const routes: Routes = [
    { path: '**', component: class DummyComponent {} },
];
Shallow.neverMock(HAMMER_GESTURE_CONFIG)
    .alwaysProvide(SomeService)
    .alwaysReplaceModule(RouterModule, RouterTestingModule.withRoutes(routes));
```

error:
```
	Error: Unexpected value '[object Object]' exported by the module 'MockOfErrorRoutingModule'
	error properties: Object({ ngSyntaxError: true })
	    at syntaxError (http://localhost:9876/_karma_webpack_/vendor.js:36465:17)
	    at http://localhost:9876/_karma_webpack_/vendor.js:52693:40
	    at <Jasmine>
	    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (http://localhost:9876/_karma_webpack_/vendor.js:52691:49)
	    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleSummary (http://localhost:9876/_karma_webpack_/vendor.js:52589:35)
	    at http://localhost:9876/_karma_webpack_/vendor.js:52676:55
	    at <Jasmine>
	    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (http://localhost:9876/_karma_webpack_/vendor.js:52654:49)
	    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._loadModules (http://localhost:9876/_karma_webpack_/vendor.js:60043:51)
	    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/vendor.js:60031:36)
HeadlessChrome 74.0.3729 (Mac OS X 10.14.2)
```

**Comment by getsaf** [comment]
Thanks for submitting the issue. The setup you mention looks correct. Nothing sticks out as being incorrect here...

I've taken your example and plugged it into this [StackBlitz](https://stackblitz.com/edit/github-ch2odb?file=examples/component-with-routing.spec.ts) and the test passes so I must be missing something. You didn't post your template or TestModule so I made some assumptions. Could you edit that StackBlitz to include your TestModule definition to help reproduce your issue? I wonder if it has something to do with the TestModule setup?

**Comment by jenCape** [comment]
@getsaf Thank you for the fast response. I've updated the modules, and test starts to fail with similar error.

here's the modules:
```
@NgModule({
    imports: [
        RouterModule.forChild([]),
    ],
    exports: [
        RouterModule,
    ],
})
export class RoutingModule { }

@NgModule({
  imports: [RoutingModule],
  providers: [{ provide: APP_BASE_HREF, useValue: '/' }],
  declarations: [TestComponent],
})
class TestModule { }
```

**Comment by kreatemore** [comment]
Hey there @jenCape - I'm sorry just can you please explain to me why do you need to export `RouterModule` in your example? Cheers!

**Comment by jenCape** [comment]
I was just following the example of angular (lazy loading)[https://angular.io/guide/lazy-loading-ngmodules], as this is one of the sub-modules of the project @kreatemore

**Comment by jenCape** [comment]
I was just following the example of angular [lazy loading](https://angular.io/guide/lazy-loading-ngmodules), as this is one of the sub-modules of the project @kreatemore

**Comment by getsaf** [comment]
While this does appear in the example, it's not necessary. You should be able to remove this export and you should be able to move forward without problems. I'll keep this issue open though because we should be able to avoid throwing that error.

**Comment by getsaf** [comment]
Update:

Turns out, replacing the module is probably not the best solution. Apparently (and I just learned this), simply importing the `RouterTestingModule` *on top* of the `RouterModule` will effectively override the original `RouterModule`.

Try `alwaysImport` instead of `alwaysReplace` like this:
```typescript
Shallow.alwaysImport(RouterTestingModule.withRoutes(...));
```

https://stackblitz.com/edit/github-ch2odb-4kv8i4?file=examples/component-with-routing.spec.ts

**Comment by jenCape** [comment]
yep, it worked. thank you @getsaf so much for the quick solution.

should i close this issue, now it's resolved?

**Comment by getsaf** [comment]
Nah, please leave it open. I think I have some more research to do. That routing module is tricky. I just tried to use the `alwaysImport` method in my example tests and ran into some issues. Hopefully this isn't blocking you but I'd like to keep this open until I can fully wrap my head around this so I'm confident I have the proper solution.

**Comment by getsaf** [comment]
Looks like you found a legit bug in shallow-render. Glad you reported it, I have a PR up that should fix it.  @kreatemore want to give that PR a review?
