### ISSUE TITLE
Have you tried this with karma-parallel?

### ISSUE THREAD

**Issue by johnwest80** [getsaf/shallow-render#116]
So I'm trying to use this with karma-parallel?  Unfortunately, tests that use your custom matchers fail with this error...

TypeError: expect(...).toHaveFoundOne is not a function

We have followed the karma-parallel instructions and added the parallel framework as shown.

configOptions.frameworks = ['parallel', 'jasmine'];

Something about parallel is keeping your custom matchers from being added, but I'm not sure what... 

We're on shallow-render 6.1.2.

Any thoughts off the top of your head?  Do you know if shallow render works with karma-parallel?  Thx!

**Comment by getsaf** [comment]
Hey @johnwest80 how's it been! Good to hear from you!

A while back when we were adding Jest support, we straightened out some issues with those matchers not being hooked up for some Jasmine/Jest setups, are you able to try [version 8.1.0](https://github.com/getsaf/shallow-render/releases/tag/v8.1.0) and see if that resolves your issue? That release included a bugfix for those types.

**Comment by getsaf** [comment]
FYI, I just created a fresh NG8 project and added shallow-render and karma-parallel (basic setup). Everything worked just fine including the matchers.

The setup is what you'd expect (just added the packages and made the changes to the karma config per the karma-parallel docs). I can publish the setup if you're interested.

**Comment by getsaf** [comment]
Hey, did you ever get this operational? Anything we can do to help?

**Comment by getsaf** [comment]
Closed due to inactivity
