### ISSUE TITLE
"not a known element" errors with shallow-render 8.2.0 when defining in "entryComponents"

### ISSUE THREAD

**Issue by antch** [getsaf/shallow-render#125]
After updating my project to Angular 8 I updated shallow-render to 8.2.2. After doing so my tests fail, both with an unknown element error:

Simply from my app module that imports an app routing module (which itself imports `RouterModule`):

```
	1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
	Error: Template parse errors:
	'router-outlet' is not a known element:
```

This is from a component that uses the PrimeNG library (where 'p-table' comes from):
```
	1. If 'p-table' is an Angular component and it has 'columns' input, then verify that it is part of this module.
	2. If 'p-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

```

In both of these cases there is no issue running `ng serve` or e2e tests which go through both of these modules.

In order to try to create a minimal repro I attempted to fork your Stackblitz Playground and update the Angular 8, and many of your tests fail: https://stackblitz.com/edit/shallow-render-ng8?file=package.json -- note that the failures still occur with non-Angular deps at the previous versions, I only upgraded them to see if it resolved the failures.

Can you advise on whether or not the Stackblitz is set up properly? Perhaps there is something I'm missing w.r.t. Angular 8 compatibility in my own app.

**Comment by getsaf** [comment]
Thanks for posting the issue:

I'm not sure why, but stackblitz does not seem to respect the max-version specified for ng-mocks in shallow-render's package.json (looks like it was upgrading past the max specified).

I implicitly included ng-mocks@7 and the tests run fine:
https://stackblitz.com/edit/shallow-render-ng8-w8ydtp?file=examples/multiple-modules.spec.ts

As for the errors...

### The routing issue
Routing is a special-case in Angular tests (even with TestBed). I have a small writeup about it in the [wiki](https://github.com/getsaf/shallow-render/wiki/FAQ#routing). Also, check out [this test](https://stackblitz.com/github/getsaf/shallow-render-stackblitz?file=examples%2Fcomponent-with-routing.spec.ts) for an example.

### The p-table issue
This is the kind of error you'll get when your component's module does not contain all the necessary dependencies (eg: imports/providers) it needs to operate. You'll want to make sure you import whichever module exports the `p-table` component into your module. If this is imported at the root, you can use `import` to include it in your test.

```typescript
shallow = new Shallow(MyComponent, MyModule)
  .import(PTableModule);
```

Alternatively, you may[`alwaysImport`](https://github.com/getsaf/shallow-render/wiki/Configuration#static-properties) to make sure it's always available in all your tests.

Hope this helps!

**Comment by antch** [comment]
Thank you for the response. I double-checked all of my imports, and they are all appropriately importing the required modules. I think that this is a regression, as simply changing the version of `shallow-render` causes the tests to go from passing to failing. I tried every minor version since 7.1.3 and narrowed it down to 8.2.0 specifically -- all of the tests pass in 8.1.0 but fail in 8.2.0.

**Comment by antch** [comment]
I was able to create a minimal reproduction of the issue:

https://stackblitz.com/edit/shallow-render-ng8-unknown-element?embed=1&file=examples/multiple-modules.spec.ts

The key is that the component is included in the module's `entryComponents` -- this is broken in 8.2.0, working in 8.1.0.

**Comment by getsaf** [comment]
Thanks for the extra detail, I'm gonna look at what was added between those versions and try to track down the culprit.

**Comment by getsaf** [comment]
It's this block:
https://github.com/getsaf/shallow-render/pull/118/files#diff-46332e32d51c32375adae1b37334b306R19-R21

The goal there was to allow entry components to be used in tests via `ng-component-outlet`. Turns out that isolating entry components in their own module for tests causes it to be isolated from the other components in the original module. I'm gonna try to restructure the test-module. I'm going to leave a test in (like the one you have in your example) that ensures we don't have this regression again.

**Comment by antch** [comment]
Ty you very much for the explanation and the quick fix!

**Comment by getsaf** [comment]
👍

Give v8.3.0 a go and see if it fixes your issue. Please report back if you still have issues!

**Comment by antch** [comment]
Works perfectly.
