### ISSUE TITLE
Using `find` method

### ISSUE THREAD

**Issue by dmnrmr** [getsaf/shallow-render#13]
Let's say I have a condition rendering in my template. I want to test that conditional rendering. `find` method throws an error about element not existing `Could not find the element you were looking for. Your test tried to access the 'prototype' property on a QueryResult but your query had no results.` I either need to wrap that into a `try/catch` block or in some different way.

Ideally I would like to determine if element exists only by using `find` method.

**Comment by getsaf** [comment]
If you're just trying to determine if the element exists, you can use:
```typescript
const {find} = await shallow.render();
expect(find('span').length).toBe(0);
```

What's going on here is that the return value from `find` is *really* a `Proxy` of `DebugElement[]` that also acts like the first item in the array of results ([see here for the implementation](https://github.com/getsaf/shallow-render/blob/master/lib/models/query-match.ts#L23)). If the array is empty, `Shallow` throws errors when it is treated as if it had results. The only way to verify an empty result is to check the array length.

Hope this helps. If not, could you post your spec?

**Comment by dmnrmr** [comment]
`const foo = find('p').length;` works great, but `const message = find('p');` throws an error. This is kind of odd.

**Comment by dmnrmr** [comment]
I am sorry. I am retarded af. While doing a copy/paste (like a pro programmer). I was trying to read `nativeElement` property of an element, that doesn't exists.

**Comment by getsaf** [comment]
Ha, all good man.
