### ISSUE TITLE
Custom matchers don't work with Jest and TypeScript

### ISSUE THREAD

**Issue by ericrav** [getsaf/shallow-render#131]
Functionally, the matchers do work, but you can get this TypeScript compiler error from `expect(find('.some_class')).toHaveFoundOne()`:

```
Property 'toHaveFoundOne' does not exist on type 'Matchers<QueryMatch<DebugElement>>'.
```

Changing the namespace declaration from `jest.ArrayLikeMatchers` to `jest.Matchers` fixes it. Also see [@types/jest](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jest/index.d.ts#L606)

**Comment by getsaf** [comment]
I referenced your type fix in another PR. It seems to fix the jest issues in another project. Give it a go with version 8.5.0

**Comment by ericrav** [comment]
> I referenced your type fix in another PR. It seems to fix the jest issues in another project. Give it a go with version 8.5.0

Thanks, I tried version 8.5.0, and it does remove this TypeScript error.
But it also caused all of the Jest matchers to have `any` type and removed any typeahead I got in VS Code as I typed `expect(...).<some_matcher>`

**Comment by hakimio** [comment]
> Thanks, I tried version 8.5.0, and it does remove this TypeScript error.
> But it also caused all of the Jest matchers to have `any` type and removed any typeahead I got in VS Code as I typed `expect(...).<some_matcher>`

I am using Jest with the latest version of shallow-render and I have perfect auto-complete working on JetBrains Webstorm IDE. Might be an issue on your end.

**Comment by hakimio** [comment]
In case someone else having issues with auto-complete, might be because you didn't add "jest" to `types` array in your `tsconfig.spec.json`:
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/spec",
    "baseUrl": "./",
    "types": [
      "jest",
      "node"
    ],
    "emitDecoratorMetadata": true
  },
  "files": [
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.spec.ts",
    "src/**/*.d.ts"
  ]
}
```

**Comment by ericrav** [comment]
@hakimio what version of TypeScript are you using? I'm on `3.4.1`.

I have Jest types set up. I only get this issue when updating `shallow-render` to 8.5.0 because of this error:
```
interface jest.Matchers<R, T>
All declarations of 'Matchers' must have identical type parameters.ts(2428)
```
from `shallow-matchers.d.ts` because it uses `jest.Matchers<T>` instead of `jest.Matchers<R>`.

It might be that different versions of TypeScript don't have this requirement.

**Comment by hakimio** [comment]
@ericrav I have `3.5.3` and I don't get any errors. Can you recreate in a github repository with Angular 8 starter app?

**Comment by ericrav** [comment]
I haven't been able to reliably recreate the issue, so I'll close for now.

To clarify, I don't get any errors running Jest, but only in the IDE (VS Code) and Intellisense.

I see this error reported in my editor:
<img width="946" alt="Screen Shot 2019-10-28 at 4 56 11 PM" src="https://user-images.githubusercontent.com/3066943/67789396-498cd100-fa4a-11e9-9575-72c714cf8db1.png">

**Comment by hakimio** [comment]
@ericrav Does it work if you replace `Matchers<T>` with `Matchers<R>`? If it does, maybe you should submit a PR?

**Comment by hakimio** [comment]
It seems you are not the only one with this issue: [PR@jasmine-marbles](https://github.com/synapse-wireless-labs/jasmine-marbles/pull/36).
