### ISSUE TITLE
Generic argument `Matchers<T>` name error for v8.5.0, jest

### ISSUE THREAD

**Issue by psychowico** [getsaf/shallow-render#141]
Ok, so when I tried to use newest version of the `shallow-render` with `jest` and I got following error from typescript (when compiling):

`Generic type 'Matchers<R, T>' requires 2 type argument(s).`

It was very confusing, because in my entire codebase and `node_modules/**` files there was no `Matchers` definition with 2 generic arguments. Only with 1 generic argument.

What I found that in newest version extending jest `Matchers` interface: https://github.com/getsaf/shallow-render/blob/master/lib/test-frameworks/shallow-matchers.ts#L17
```ts
interface Matchers<T> extends ShallowMatchers { }
```

It use `T` as argument name.
But for `jest` standard typing lib the argument is named `R`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/855c08045694f8ec34bf69d13743e8a9d7a13038/types/jest/index.d.ts
```ts
interface Matchers<R> {
  ...
```

This looks like no important thing, but this is the source of the `Generic type 'Matchers<R, T>' requires 2 type argument(s).` error. When I edit `shallow-renderer` source code and change `T` to `R` all works correctly.

**Comment by getsaf** [comment]
Thanks for this fix. Hopefully it solves the Jest type issues for others that have reported.

**Comment by getsaf** [comment]
Tried this is a beta-release and it checks out!! Thanks again! Closing this issue (hopefully for the last time).

**Comment by psychowico** [comment]
Thanks!
