### ISSUE TITLE
angular 8 unmet peer dependency

### ISSUE THREAD

**Issue by pablomaurer** [getsaf/shallow-render#148]
I get warning using angular 8 about:

├── UNMET PEER DEPENDENCY @angular/compiler@>=5.x <=7.x
├── UNMET PEER DEPENDENCY @angular/core@>=5.x <=7.x
├── UNMET PEER DEPENDENCY @angular/forms@>=5.x <=7.x

**Comment by getsaf** [comment]
This is an issue with overly restrictive ng-mocks dependencies. The version of ng-mocks shallow uses is compatible with Angular 8 but I was unable to convince the ng-mocks maintainer to fix the dependencies in this version.

It'll be resolved when shallow starts narrowing Angular version support in future releases Eg: shallow 9 will only support Angular 9 and we'll follow that path from then forward.

Here's the conversation about it from another post:
https://github.com/getsaf/shallow-render/issues/137#issuecomment-538775651

**Comment by pablomaurer** [comment]
thanks for the information =)
