### ISSUE TITLE
How to mock property of dependency?

### ISSUE THREAD

**Issue by dmnrmr** [getsaf/shallow-render#16]
Can't wrap my head around this. So I have this code:
```
constructor(private store: FooStore) {
    this.foo= this.store.foo
}
```
Is it possible to mock what `this.store.foo` returns?

**Comment by getsaf** [comment]
Definitely!

Let's consider this to be your component:
```typescript
@Component({selector: 'my-component'})
class MyComponent {
  public foo: string;

  constructor(private store: FooStore) {
    this.foo = this.store.foo;
  }
}
```

In your spec you can mock anything from the `FooStore`
```typescript
describe('MyComponent', () => {
  let shallow: Shallow<MyComponent>;
  beforeEach(() => {
    shallow = new Shallow(MyComponent, MyModule);
  });

  it('sets foo from the FooStore', async () => {
    const {instance} = shallow
      .mock(FooStore, {foo: 'Mock Foo Value'});
      .render();

    expect(instance.foo).toBe('Mock Foo Value');
  });
});
```

If all the specs in that file need that same mock, you may apply your mocks in the `beforeEach` block like so:
```typescript
beforeEach(() => {
  shallow = new Shallow(MyComponent, MyModule)
    .mock(FooStore, {
      foo: 'Mock Foo Value',
      bar: 'Mock Bar Value', // <-- Also, you may mock multiple properties/methods at once!
      someServiceCallMethod: () => Promise.resolve(true)
    })
})
```

Mocks also stack so if you mock a service property in your `beforeEach`, you can override them in a specific spec.

So if your  `beforeEach` has `.mock(FooService, {foo: 'Mock Foo'})` to cover the general use-case, but you have a spec where you want foo to be `null` you may, in your spec do `.mock(FooService, {foo: null})` which will override the `beforeEach` mock for *that specific test*.

I have some example specs that mock service/injectable properties [here](https://github.com/getsaf/shallow-render/tree/master/lib/examples) that may help too.
