### ISSUE TITLE
feat: Shallow.alwaysMockPipe()

### ISSUE THREAD

**Issue by bamsir** [getsaf/shallow-render#163]
We have a pipe that is used in practically every one of our components. We also have a mock pipe implementation that we use in every shallow test with `.mockPipe()`. It would be create to just do this once globally with `Shallow.alwaysMockPipe()` instead.

**Comment by getsaf** [comment]
Oh wow, I can't believe this was not added already. Seems easy, I'll see if I can get it added over the weekend.

**Comment by getsaf** [comment]
Added and released [v0.9.5](https://github.com/getsaf/shallow-render/releases/tag/v9.0.5).

https://getsaf.github.io/shallow-render/#global-pipe-mocks-with-alwaysmockpipe
