### ISSUE TITLE
How to validate ngModel is set correctly

### ISSUE THREAD

**Issue by DW8Reaper** [getsaf/shallow-render#167]
I am testing a component (lets call it TestComponent) that uses a custom element (for example CustomRadioGroup) which implements ControlValueAccessor. Something like this:

```
@Component(
selector: 'test-component'
template: `
  <custom-radio-group [options]="optionList" [(ngModel)]="selectedOption"></custom-radio-group>
`
export class TestComponent {
  public selectedOption = 'theDefaultOption';
}
```

when I write a test I can validate that ```selectedOption``` in my TestComponent is set correctly but how do I validate that I setup the NgModel correctly for CustomRadioGroup? 

So imagine my test is:
```
beforeEach(() => {
  shallow = new Shallow(TestComponent, TestModule);
})

it('should set the default radio option', async () => {
  rendering = await shallow.render();
  const radioGroup = rendering.findComponent(CustomRadioGroup);
  expect(radioGroup.value).toEqual('theDefaultOption');
})
```
but this test will always fails since radioGroup's component type CustomRadioGroup is a mocked component (which is good I am not testing its internals) and the value is never changed. 

I looked at the ng-mocks MockControlValueAccessor and looks like they just send and writeValue calls into the abyss. 

How can I easily verify ngModel of a component inside my component?

**Comment by getsaf** [comment]
I don't have a ton of experience with these kinds of implementations but I think [this](https://stackblitz.com/github/getsaf/shallow-render-stackblitz?file=examples%2Fcomponent-with-forms.spec.ts) is what you're looking for.

```ts
@Component({
  selector: 'foo',
  template: `
    <input id="name" type="text" [(ngModel)]="name" />
  `
})
class FooComponent {
  name = 'Brandon';
}
```

```ts
  it('updates the name property when the input changes', async () => {
    const { find, instance, fixture } = await shallow.render();
    find('#name').nativeElement.value = 'foo';
    find('#name').nativeElement.dispatchEvent(new Event('input'));
    fixture.detectChanges();

    expect(instance.name).toBe('foo');
  });
```

This does verify that the NgModel directive is assigned on your child component by sending a value through the directive with a change event.

If you want to avoid using the instance, you can verify the value on the `NgModel` directive directly:
```ts
  it('updates the name property when the input changes', async () => {
    const { find, fixture, findDirective } = await shallow.render();
    find('#name').nativeElement.value = 'foo';
    find('#name').nativeElement.dispatchEvent(new Event('input'));
    fixture.detectChanges();

    expect(findDirective(NgModel, {query: '#name'}).value).toBe('foo');
  });
```

Let me know if this works out for you.

**Comment by DW8Reaper** [comment]
Thanks for the detailed response, that is almost what I want but imagine FooComponent wasn’t mine it was part of a library. I’m testing a component that uses FooComponent and as such FooComponent is mocked by Shallow. 

How would I confirm that I am sending the correct values to FooComponent’s ngModel binding?

Let me know if that doesn’t make sense and I can try spin up a StackBlitz example.

**Comment by getsaf** [comment]
I think I understand what you're saying but I don't follow the logic. The example I posted shows how to assert that the expected `ngModel` are being applied to a mocked component.

If you also need to verify that `FooComponent` does the right thing with the `ngModel` then you could use `dontMock(FooComponent)` to prevent mocking. This would allow you to test the integration of the component-under-test and `FooComponent` while mocking everything else.

It might help if you could provide a StackBlitz example that illustrates the question.

**Comment by DW8Reaper** [comment]
Thanks @getsaf that is probably the best option right now. Maybe when I have some free time I will dig into ng-mocks and see if I can easy put in a PR to put ng-model on the mocks.
