### ISSUE TITLE
Sister package: ng-vacuum

### ISSUE THREAD

**Issue by hmil** [getsaf/shallow-render#168]
Hi there,

This is just to let you know about [ng-vacuum](https://github.com/hmil/ng-vacuum), a library I created to make writing strict unit tests in angular easier.
ng-vaccuum is using shallow-render under the hood to render angular components in isolation, and combines it with [OmniMock](https://github.com/hmil/omnimock) to provide automatic mocks for services.

This library is obviously very opinionated and geared towards strict one-class-at-a-time unit tests (what you could call the "bottom of the test pyramid"). It greatly reduces the amount of boilerplate required there.

I've introduced this library at work after I discovered that our test suites did not scale well. This appeared to be caused by the difficulty to keep each test suite contained within a single layer of abstraction, leading to leaks of abstraction and coupling between layers*. So far, the feedback from my coworkers has been positive.

Please check it out if you can and let me know what you think about it, feel free to add a cross link in the readme if you think it is worth it and close this issue or keep it open, whatever. This is just an FYI so you know that your work is appreciated and how it is used. I'm not asking for publicity or anything.

Cheers.

*Most junior developers struggle with this, and in my experience even advanced developers sometimes don't see the value to keep tests strictly contained within an abstraction layer. ng-vacuum forces isolation such that one cannot really introduce accidental coupling in tests, provided the production code is well architectured obviously.

**Comment by getsaf** [comment]
This looks interesting, thanks for the head's up! I really like the omni-mock style and I like how readable the final tests are.

On a related note, I may soon add basic support for service testing in Shallow too but it's really just an opportunity to allow using shallow's module-mocking to be used to test a service.

If it's ok with you, I may add a link to ng-vacuum somewhere in the docs if I get around to adding a "who uses shallow" section.

If you need anything or need a hand in ng-vacuum just let me know.
