### ISSUE TITLE
"Cannot instantiate cyclic dependency! NgControl"

### ISSUE THREAD

**Issue by akaztp** [getsaf/shallow-render#188]
After struggling for a couple of days with an error on tests when upgrading our project to Angular 10 (and shallow-render), I've found the solution in your playground project on stackblitz.

```javascript
        .provideMock({
          provide: NG_VALUE_ACCESSOR,
          useClass: DefaultValueAccessor,
          multi: true,
        });
```
This was what was missing from our tests so we don't get an error like:
```
		Error: Template parse errors:
		Cannot instantiate cyclic dependency! NgControl (
		  [ERROR ->]<nz-select #selector
		    (ngModelChange)="onChange($event)"
		    (nzBlur)="onTouched()"
		"): ng:///ShallowTestModule/FormControlImplementationEaseComponent.html@1:2
		
		    at syntaxError (/home/ztp/repos/bee/packages/compiler/src/util.ts:108:17)
		    at TemplateParser.Object.<anonymous>.TemplateParser.parse (/home/ztp/repos/bee/packages/compiler/src/template_parser/template_parser.ts:108:13)
```

I've forked your playground project, and upgraded shallow-render to v10.2.0:
https://stackblitz.com/edit/github-mpmyc2?file=examples/test.spec.ts

If I delete that `provideMock()` code from your `example/component-with-forms.spec.ts` still works, but not when the `ngModel` is applied to a component that implements `ControlValueAccessor`, like on the file "test.spec.ts" on my stackblitz instance.

I'm not understanding this completly so several doubts come across my mind:
- Is `DefaultValueAccessor` provided by Angular by default on `NG_VALUE_ACCESSOR` ?
- Should this `provideMock()` code above be added by shallow-render automatically besides `neverMocking(NG_VALUE_ACCESSOR)`.

Not sure even if these doubts make sense...
Hope you got a more clear view on this.
Thanks!

**Comment by getsaf** [comment]
Thanks for posting the issue. It seems there are several ways to hang myself with mocking component providers. In [this instance](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/select/select.component.ts#L65), it's using a [forward-ref](https://github.com/angular/angular/blob/10.2.0/packages/core/src/di/forward_ref.ts#L29-L48) which is cumbersome to mock. I am starting to reconsider whether it was a good idea to implement component-level provider mocking in the first place.

The original goal was to solve for some weirdness when testing with Angular's Forms but I think I like your suggested solution  better than trying to mock all providers for mock components. I will try your suggestion out in a beta build and post here when it's ready to test.

**Comment by getsaf** [comment]
I just published a beta release (v10.2.1-0), give this a go and let me know how it goes. If it works out, I'll make this the next full release.

`npm i -D shallow-render@10.2.1-0`

**Comment by akaztp** [comment]
Yes, rremoved 
```javascript
  Shallow.alwaysProvide({
    provide: NG_VALUE_ACCESSOR,
    useClass: DefaultValueAccessor,
    multi: true,
  });
```
and all good! Many thanks!

**Comment by kevinbeal** [comment]
This fixed the issue for me as well. Thank you @getsaf!

There was a place where `.provideMock()` stopped working the way it previously had though. I don't see anything obvious about the particular usage I had (as other calls to `.provideMock` continue to work). But the mock provided didn't get used. It just used the original service.

It could be user error on my part, but I just wanted to throw that out there in case there actually is an issue.

**Comment by getsaf** [comment]
> There was a place where `.provideMock()` stopped working the way it previously had though. I don't see anything obvious about the particular usage I had (as other calls to `.provideMock` continue to work). But the mock provided didn't get used. It just used the original service.

I meant to follow up with you on this @kevinbeal. Did you ever figure out the issue there? Do you think it's a bug?

**Comment by kevinbeal** [comment]
Thanks. I just checked my commit log for clues and discovered an error on my part.

I was doing the equivalent of this:

```typescript
shallow.provideMock(MyService, { provide: MyService, useValue: {...} })
```

I was using `.mock()` previously and modified it, leaving the first parameter erroneously while fixing the second.

Perhaps that was find in some previous version of `shallow-render` because it just used the second one overwriting(?) the first one. And then in an update that behavior changed. Idk, just guessing.
