### ISSUE TITLE
RouterTestingModule

### ISSUE THREAD

**Issue by impankratov** [getsaf/shallow-render#19]
Is there any way to add `RouterTestingModule` to TestingModule? I see that we can manipulate mocking of components, providers, but nothing about modules.

I'm used to test "href" attribute of anchor elements in my test, plus I would like to test the click event (to expect Router.navigate() to have been called for example).

**Comment by getsaf** [comment]
Yeah, that seems totally do-able. I suspect it'll be something like:
```typescript
shallow
  .import(RouterTestingModule)
  .dontMock(RouterTestingModule) // Assuming you want the real thing?
  .render();
```
I'll add an `always` version too so you can do it globally in your test-shim like so:
```typescript
Shallow
  .alwaysInclude(RouterTestingModule)
  .neverMock(RouterTestingModule);
```

I'll give it a shot for v0.12 maybe early next week?

**Comment by impankratov** [comment]
@getsaf looks cool, thanks for a quick response

I got some thoughts (maybe I'm just not getting the actual shallow-render logic?). Take this code for example:

```
////// Module Setup //////
@Component({
  selector: 'big-text',
  template: '<h1><ng-content></ng-content></h1>',
})
class BigTextComponent {}

@NgModule({
  imports: [RouterModule] // original RouterModule, it somehow required by BigTextComponent
  declarations: [BigTextComponent]
})
class BigTextModule {}
//////////////////////////
describe('simple component example', () => {
  let shallow: Shallow<BigTextComponent>;

  beforeEach(() => {
    shallow = new Shallow(BigTextComponent, BigTextModule);
  });
```

In this case, shallow-render will try to mock out all module contents, including the RouterModule. But, we want to provide RouterTestingModule instead of RouterModule. I don't know it it's actually possible at this point, haven't looked at the sources here.

So for me it's more logical to do something like 
```
shallow
  .provide(RouterModule, { useClass: RouterTestingModule })  // again, I'm not sure if this possible, just seems a little bit easier to understand what's going on
  .render();
```
instead of your example:
```
shallow
  .import(RouterTestingModule)
  .dontMock(RouterTestingModule)
  .render();
```
Also, it's not clear for me (at least right now), what will happen with original RouterModule imported in BigTextModule? Will it be overridden by RouterTestingModule?

**Comment by getsaf** [comment]
It would be nice if Angular worked that way but they treat modules different from normal providers. With Shallow, the `provide` method is analogous to the `provides` array of a module so I was thinking I could use `import` to target the `imports` array.
```testbed
@NgModule({
  imports: [CommonModule],
  providers: [{provide: MyClass, useValue: MyClassMock}]
})
class MyModule {}
```

You raise a good question about what happens to the actual `RouterModule`. It sounds like we should be *replacing* `RouterModule` with `RouterTesting` module for another instead of having both modules end up in the test environment.

I'll keep that in mind. Maybe the solution would look more like:
```typescript
shallow
  .replaceModule(RouterModule, RouterTestingModule);
```

**Comment by getsaf** [comment]
Yo @impankratov I got you covered in v0.12.0.

Should be just a matter of either this in your spec:
```typescript
shallow
  .replaceModule(RouterModule, RouterTestingModule);
```

or this in your karma-shim:
```typescript
Shallow
  .alwaysReplaceModule(RouterModule, RouterTestingModule);
```

I wrote an example for the pattern [here](https://github.com/getsaf/shallow-render/blob/master/lib/examples/using-replacement-modules.spec.ts).

Thanks for your help on this, it's a good feature.

**Comment by impankratov** [comment]
@getsaf wow, thanks for such quick update, will definitely try this!
