### ISSUE TITLE
Angular 12 support

### ISSUE THREAD

**Issue by Timebutt** [getsaf/shallow-render#200]
Angular 12 was [recently released](https://blog.angular.io/angular-v12-is-now-available-32ed51fbfd49), and when upgrading my repo to Angular 12 using NPM 7 I'm getting error messages about peer dependencies not being correct:

```
npm WARN Could not resolve dependency:
npm WARN peer @angular/common@"11.x" from shallow-render@11.0.0
npm WARN node_modules/shallow-render
npm WARN   dev shallow-render@"11.0.0" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @angular/compiler@12.0.0
npm WARN node_modules/@angular/compiler
npm WARN   @angular/compiler@"12.0.0" from the root project
npm WARN   4 more (@angular/compiler-cli, ...)
```

I'm guessing updating this repository to support Angular 12 isn't a lot of work? I'm definitely willing to help out and submit a PR!

**Comment by getsaf** [comment]
Dang, didn't even notice that Angular 12 upgrade.. I'll see if I can verify and release NG12 support today.

**Comment by getsaf** [comment]
Done!
Sorry, had to test it against an actual NG12 project. Looks good, here's the release:
https://github.com/getsaf/shallow-render/releases/tag/v12.0.0

**Comment by Timebutt** [comment]
Awesome work, thanks! 🙌
