### ISSUE TITLE
Testing ng-template child rendering

### ISSUE THREAD

**Issue by vticnikisi** [getsaf/shallow-render#215]
With reference to existing issue #165, how should I test rendering of the child component <ng-template>?

I have created simple test case

https://stackblitz.com/edit/github-3wajlf-ruzucl?file=examples%2Ftemplate.spec.ts

**Comment by getsaf** [comment]
It looks like the sub-content doesn't actually render in your example (even outside of a test):

https://stackblitz.com/edit/angular-ivy-vswyha?file=src%2Fapp%2Fawesome.component.ts

**Comment by getsaf** [comment]
Closed due to inactivity. Appeared to be a non-issue
