### ISSUE TITLE
Support for Angular 14

### ISSUE THREAD

**Issue by bitsmuggler** [getsaf/shallow-render#219]
I would be very grateful if you have the time to upgrade to the latest Angular version.

**Comment by johan-s-ie** [comment]
Hey, any chance you found a work around in the meantime compatible with Angular 14?

**Comment by bitsmuggler** [comment]
@johan-s-ie Unfortunately, not.

**Comment by martibenn** [comment]
Hi !
up on this topic 🙂
Since ng 13 is a [fixed peerDependency](https://github.com/getsaf/shallow-render/blob/master/package.json#L55), it block us from migration to ng14
🙏

**Comment by getsaf** [comment]
Hey all sorry for the delay, work has been a bit much for me over the last several months.

Any help with this maintaining this project would be greatly appreciated!

**Comment by bitsmuggler** [comment]
@getsaf Thanks!!
