### ISSUE TITLE
[Question] Testing of functions, possible?

### ISSUE THREAD

**Issue by shrestaz** [getsaf/shallow-render#25]
First of all, great library. Thanks for the hard work.

Secondly, is it possible to test functions defined in the component class? All the examples/documentation tests against the template. If it is possible, could you please provide a small example?

**Comment by shrestaz** [comment]
Hi again. So I tried implementing shallow-render in my project but got the error `Failed: Cannot read property 'injector' of null`.

[I've created a stackblitz project to recreate the error with your example above.](https://stackblitz.com/edit/angular-testing-shallow-render) 
// _Please ignore the error_ `TypeError: _angular_core.ɵclearOverrides is not a function`

Do you have any suggestions? Thanks :relaxed:

**Comment by getsaf** [comment]
I had some issues with that Stackblitz project (maybe you forgot to save some changes?).

I forked it and all I did was upgrade to angular 5.2 to resolve the dependency issues and it worked, your test passed!

https://stackblitz.com/edit/angular-testing-shallow-render-cv1gz7

**Comment by shrestaz** [comment]
So it doesn't work with Angular 6, which is used in my project. I'll come back to this when Angular 6 is supported. Great library nonetheless :tada:.

**Comment by getsaf** [comment]
FYI, NPM is having some issues this morning with newly published packages:
https://status.npmjs.org/incidents/3rjzvts6v98k

I haven't been able to `npm install` version 6 yet, but once NPM resolves that issue, we should be good to go.
