### ISSUE TITLE
Angular 17 support

### ISSUE THREAD

**Issue by meierw** [getsaf/shallow-render#251]
Since Angular 17 is out now, perhaps this library should get updated to support that? Thanks 🙂

**Comment by daancallaert** [comment]
@getsaf Having an Angular 17 build would be lovely

**Comment by johnwest80** [comment]
@getsaf brandon, hi there. can you possibly create an angular 17 build? thx! and i haven't forgotten about getting you more info about the test run speeds around caching.  just haven't had time to dig back into it.

**Comment by getsaf** [comment]
It's on my to-do list. I just need to get the deps changed and make sure
the tests still pass.

**Comment by getsaf** [comment]
I got v17 out. There were no code changes , I just updated the deps and everything else was compatible.

@johnwest80 out of curiosity, are there lots of `alwaysImport` or `alwaysProvide`being used in your setup? Do tests run quickly if you run a small batch or just a single file?
