### ISSUE TITLE
Warning with angular6

### ISSUE THREAD

**Issue by dauledk** [getsaf/shallow-render#27]
Thanks for the awesome library. 

I get this error when using shallow-render with angular v6:

```
npm WARN @angular/common@5.2.11 requires a peer of rxjs@^5.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/core@5.2.11 requires a peer of rxjs@^5.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/forms@5.2.11 requires a peer of rxjs@^5.5.0 but none is installed. You must install peer dependencies yourself.
```

I am using shallow-render version `0.13.0`

**Comment by getsaf** [comment]
FYI, NPM is having some issues this morning with newly published packages:
https://status.npmjs.org/incidents/3rjzvts6v98k

I haven't been able to `npm install` version 6 yet, but once NPM resolves that issue, we should be good to go.
