### ISSUE TITLE
Great testbed!

### ISSUE THREAD

**Issue by st-clair-clarke** [getsaf/shallow-render#35]
Congrats with such an intuitive package.

Request: Could we have a shallow-cli to generate the boiler-plate. This would even reduce the amount of code we write.

Regards

**Comment by getsaf** [comment]
First, thanks for using Shallow and thanks for the question.

Doesn't Angular already supports custom templates for specs? I would encourage using the angular-cli way if you want to customize/formalize your spec structure. The boilerplate for Shallow is so small, it probably wouldn't be a bad idea to just use a [code-snippet](https://code.visualstudio.com/docs/editor/userdefinedsnippets) feature in you editor/IDE. I may do this myself.
