### ISSUE TITLE
How do I test reactive forms?

### ISSUE THREAD

**Issue by juracy** [getsaf/shallow-render#37]
I have components those subscribe valueChanges of a FormGroup, but I can't trigger them!

**Comment by getsaf** [comment]
ReactiveForms violate so many best-practices that I'd actually recommend using the real thing by doing a `dontMock(ReactiveFormsModule)` or better yet, `neverMock(ReactiveFormModule)`. Fortunately, they don't use any other external dependencies so they're safe to use in isolation.

**Comment by juracy** [comment]
Ok, my problem was in pipe chains of valueChanges...

Thanks!
