### ISSUE TITLE
Cannot Seem to .replaceModule() when using .forRoot() type modules

### ISSUE THREAD

**Issue by kevinbeal** [getsaf/shallow-render#43]
The "component with routing" example you have on Stackblitz isn't quite right.

In a real component/app, I would be using `RouterModule.forRoot()` and not simply `RouterModule`.

When I add that to the example, it breaks.

[Here's my Stackblitz fork](https://stackblitz.com/edit/shallow-render-mau9qp?file=examples/component-with-routing.spec.ts).

I immediately get the following error:

> Error: Unexpected value '[object Object]' imported by the module 'DynamicTestModule'. Please add a @NgModule annotation.

I thought it might work similar to `.dontMock()` in that you need to save a reference to `var = Module.forRoot()` and put `var` in `.dontMock(var)`. That didn't work either. I get the error:

> TypeError: this.appInits[i] is not a function

I'm guessing that this means the `.replaceModule()` line is ignored altogether.

Do I also need to use `.provide()` or something?

Also, is there a way to send you a few dollars/btc for all the work you've done? It's been very helpful for me at work.

**Comment by getsaf** [comment]
Thanks for the StackBlitz. I'm going to check this out over the holiday. Hopefully I'll get it knocked out. I do see that the RouterModule doesn't seem to be a module itself, it just has static methods that return `ModuleWithProvider`. That's a start. I'll let you know what I find.

**Comment by getsaf** [comment]
Dude, this was a great catch. Sorry, this shows my lack of experience with Angular Routing. I did figure out the issue though. In a nutshell, shallow's strict "mock everything" approach mocks some stuff that we want to skip (you were onto this in your example). The trick seems to be the need to tell Shallow, not to mock any of the routing stuff.

```typescript
  beforeEach(() => {
    shallow = new Shallow(GoHomeLinkComponent, GoHomeModule)
      //////////////////////////
      // These are good candidates for global setup
      // using `neverMock` and `alwaysProvide`
      .dontMock(routerModuleRef) // <-- The key line here.
      .provide({provide: APP_BASE_HREF, useValue: '/'})
      .dontMock(APP_BASE_HREF)
      ///////////////////////////
      .replaceModule( // Weird thing is that this doesn't seem necessary?!? Am I missing something?
        routerModuleRef as any, // The need to cast here is a bug!! I'll have this fix in for the next release ;-)
        RouterTestingModule.withRoutes(routes)
      );
  });
```

I updated the official [StackBlitz](https://stackblitz.com/edit/shallow-render?file=examples%2Fcomponent-with-routing.spec.ts) with the fix.

There's one think I'm still not sure of. I noticed that if I remove the `replaceModule` block, the test still passes!!! It's like we don't even need/use the testing module. I'd like to leave this issue open until I figure out why. **Do you have any ideas? Should I remove the `RouterTestingModule` from the example or is it useful for some other reason?**

Side note, thanks for the donation offer. I feel sort-of bad taking money but I don't really have a good reason not to :-). I appreciate the support and the help I get from the community and that's enough to keep this project going, but if you'd like to buy me a beer, I'll take it. I have square cash and pay-pal using getsaf@gmail.com.

**Comment by kevinbeal** [comment]
Thanks!

And I think the example is good. At least people can see how to write tests with routes using shallow-render.

Angular testing examples across the internet are mostly confusing and contradictory. Speaking for myself, I just want something that works, and your example works from I can see, and with little setup. :)
