### ISSUE TITLE
Is there a way to add imports?

### ISSUE THREAD

**Issue by kevinbeal** [getsaf/shallow-render#44]
When you:
- use the NGRX Store module
- use it inside of a feature module
- use it in a component within that module
- and you want to test it,
then they require you to add an additional import.

It looks like this:

```typescript
imports: [ 
    StoreModule.forRoot({}), // This is the extra import
    StoreModule.forFeature('yourFeature', fromFeature.reducers)
]
```

Without the extra import, you can't use the `Store` service within your component. It complains about missing providers.

But you can't just add `StoreModule.forRoot({})` to your feature module since it would defeat the whole purpose of having `StoreModule.forFeature('yourFeature', fromFeature.reducers)`. The extra import is only for the test.

Is there a way to add new imports?

I recall there used to be an `.imports()` method on the shallow class instance, but it's no longer there.

**Comment by kevinbeal** [comment]
I realize now that the NGRX people don't recommend what I said. Instead, they would do something like `.replaceModule()` with `StoreModule.forRoot({ .'yourFeature', combineReducers(fromFeature.reducers) })`.

So, importing something new wouldn't really help me.

I'm going to close the issue.

**Comment by getsaf** [comment]
Hey Kevin, sorry I didn't get back to you in time. I worked with someone else on testing with ngrx. And published a bug fix in the process, check out #36 and it may give you some direction on testing with ngrx.

**Comment by kevinbeal** [comment]
For reference, if someone else finds this wanting to add an import, you could do it like so:

```typescript
export const addImports = <T>(module: Type<T>, imports: any[]) => {
    @NgModule({
        imports: [
            ...imports,
            module,
        ]
    })
    class ModuleForSpecs {}
    Shallow.neverMock(module);
    return ModuleForSpecs;
};

new Shallow(MyComponent, addImports(MyModule, [BrowserAnimationModule]))
```

**Comment by kevinbeal** [comment]
It seems that this method makes `.replaceModule()` stop working. `.replaceModule(RouterModule, RouterTestingModule)` does not replace `RouterModule` when I use this approach.

I'm assuming this is because it is trying to do the replacement at the level of `ModuleForSpecs` rather than `MyModule`.

I am still playing with it but in the meantime, I've added I'm adding a remove imports option to my `addImports` function that removes it from the module reference directly. That may have consequences for other tests that I don't intend though.

In cases where I just want to add an import instead of replacing one, it would be convenient if there were a method on the shallow instance.

At any rate, if anyone is trying to use NgRx with shallow-render, here is what I did:

```typescript
// Creating specific instances of the modules (ModuleWithProviders)
export const FluentListStoreModule = StoreModule
	.forFeature('fluentList', reducers);

export const FluentListStoreTestingModule = StoreModule.forRoot({
	fluentList: combineReducers(reducers)
});

// I'm adding FluentListStoreModule to my module elsewhere

// Replacing the specific references
shallow.replaceModule(FluentListStoreModule, FluentListStoreTestingModule)
```

**Comment by getsaf** [comment]
I've gone back and forth about adding a `.include()` method in Shallow, and I feel like it would encourage bad practices. Your example and solution for replacing a specific module makes more sense to me because it guarantees that your original component module *does* have the the store module included and that module should just be replaced by your testing module. This also follows the angular TestModule pattern.

I feel like if I allow `.include()` in Shallow, it would allow for testing a component in an unrealistic test environment because the developer could simply create an empty component module in their app and simply include whatever they wanted in their tests.

**Comment by kevinbeal** [comment]
That makes sense to me.

I thought it would be necessary to have an `.include()` for the NgRx example, and I was wrong. I ended up doing it more in line with how the NgRx guys want you to write tests (for feature modules).

I have another case that may also have some simpler/better workaround that I just haven't figured out yet.

It basically comes down to only loading `BrowserAnimationModule` in the root module for my actual app (because of lazy loading https://github.com/angular/angular/issues/15829) but needing it for my tests too. In this case it's adding an import rather than just replacing one. (Or at least that's what it seems to be).
