### ISSUE TITLE
Typo on Querying example in wiki

### ISSUE THREAD

**Issue by checketts** [getsaf/shallow-render#50]
On https://github.com/getsaf/shallow-render/wiki/Querying#example

the template `{{text}}` should be `{{label}}` (and probably should be renamed so it doesn't get confused with the `<label>` element anyways)

Current:
```
<h1 *ngIf="big" class="large">{{text}}</h1>
    <label *ngIf="!big">{{text}</label>
```

Should be
```
<h1 *ngIf="big" class="large">{{label}}</h1>
    <label *ngIf="!big">{{label}}</label>
```

Also missing a `}` on the second line.

**Comment by getsaf** [comment]
Hey, I really appreciate you reporting these issues with the docs. Since you've been reading through the docs, I'd like to pick your brain for a moment.

It's difficult for me to understand how useful the docs are because I'm so close to the project. Do you find that they are sufficient in explaining how the library works? Just curious from a user's point of view what you find useful or missing.

**Comment by checketts** [comment]
The docs have been very helpful. The reason I found the two parts were because I was reading them so closely as a beginner.

My background is on the (strongly typed) backend, and I really like testing my code. So I really appreciate the project.

Here are my impressions of the docs:
Home - strange that it us a duplicate of the readme
Examples - useful for reference
Getting Started - This is the most important, perhaps it should be the home page of the wiki
Jasmine Matchers - useful for reference (but didn't apply to me since I'm using Jest)
Mocking - Also essential, since with everything being shallow, mocking is important
Querying - Important for verification/assertions.
QueryMatch Class - reference
Releases - refernce
Rendering Class - good reference
Shallow Class - this might be better named as 'global config', reference
Why? - good overview of projects vision

So in review, raising the getting started, mocking, and querying pages would be a good idea to help the user find the most useful info first.

Thanks again for this great project! The type safety and simplicity has been fantastic!

**Comment by getsaf** [comment]
Dude, thanks for going out of your way to help out. I'm going to adjust my docs to your feedback.
