### ISSUE TITLE
Error when a component in project has no selector

### ISSUE THREAD

**Issue by Timebutt** [getsaf/shallow-render#57]
Hi,

I started using `shallow-render` today, as it seems to perfectly align with how we want to test our Angular application. So far so good, if it weren't for the fact that I currently keep running into the same error that's blocking me from writing tests using `shallow-render`.

I'm currently testing a really easy component using the following setup:

```
let shallow: Shallow<OverviewCourseComponent>;

beforeEach(() => {
    shallow = new Shallow(OverviewCourseComponent, UIModule);
});

it('should create', async () => {
    const { instance } = await shallow.render('<overview-course></overview-course>');
    expect(instance).toBeTruthy();
});
```

I get thrown following error however:

```
Directive MockOfHeaderPickerComponent has no selector, please add it!
```

Analysing this error, it seems to originate from this [HeaderPickerComponent](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/date-picker/header-picker.component.ts) that is part of `ng-zorro-antd`, a UI library I use.

As the error specifies: this specific component does not have a selector defined. This specific component is part of an external repository I have no control over, so adding one is not possible. 

Is there a way around this issue, or is this a problem with the current implementation of `shallow-render`? I'm currently using version `6.1.2` in my Angular `6.1.4` project.

Thanks!
Nils

**Comment by getsaf** [comment]
I really like your idea @jorisdesmedt, I had a hunch and confirmed that mutating those selectors after pulling them out of the jitReflector doesn't actually change them on the component itself. However, TestBed does have a way to override metadata on components so I took your idea and worked it in using `TestBed.overrideDirective`.

Check out #58. I'll get this released as soon as possible.

Sorry for coding this up myself was pretty happy to have the offer to add the PR. I'm interested in growing my collaborators and getting more community support going for this project. I added you

**Comment by getsaf** [comment]
Released [6.1.3](https://github.com/getsaf/shallow-render/releases/tag/v6.1.3).

I'd like to leave this issue open until you can confirm that it resolves your problem. Thanks for the bug report, this fix will definitely help others down the road.

**Comment by Timebutt** [comment]
I'll pull the new version, have a look and let you know ;)

**Comment by getsaf** [comment]
Any word on this?

**Comment by Timebutt** [comment]
Hi @getsaf: your changes sure did work, as I got it working correctly. I just need some more time to take a deep dive with this, and implement it in our repository. We're kinda swamped with other stuff coming out now, I hope I can take some time soon to set up our configuration with `shallow-render`.

I'll get back to you!

**Comment by getsaf** [comment]
Woohoo! 🍺
