### ISSUE TITLE
Entry Component can't be found, but is in module definition

### ISSUE THREAD

**Issue by kevinbeal** [getsaf/shallow-render#61]
I created a Stackblitz example showing the issue: https://stackblitz.com/edit/shallow-render-angular?file=examples%2Findex.ts

I'm using the dynamic component loading pattern described in the angular guide here: https://angular.io/guide/dynamic-component-loader

The error that displays:
> Error: No component factory found for TestEntryComponent. Did you add it to @NgModule.entryComponents?

I added the entry component to the module definition, but it didn't help:

```
@NgModule({
  declarations: [OuterComponent, TestHostDirective],
  entryComponents: [TestEntryComponent]
})
class TestModule {}
```

I also tried to use `.dontMock(TestEntryComponent)` but that didn't help either :/

**Comment by getsaf** [comment]
I did some searching and it looks like there is an open issue for [TestBed to support entry components in test modules](https://github.com/angular/angular/issues/10760) 👎

A workaround mentioned in the thread is to wrap the components in a `TestHostModule` and a `TestHostComponent` in the spec file. I've taken your StackBlitz example and [implemented the workaround suggested in the Angular issue](https://stackblitz.com/edit/shallow-render-angular-77guht?file=examples/using-entry-component.spec.ts).

**Comment by kevinbeal** [comment]
Thank you!

I found I could skip the step of creating a new test component if I used the standard `shallow.render('template', options)` syntax rather than the `shallow.render(options)`.

It looks like the shallow render method creates a new component for me in that case.
