### ISSUE TITLE
nativeElement.disabled always returning false

### ISSUE THREAD

**Issue by ticklemycode** [getsaf/shallow-render#65]
I created a stackblitz in an attempt to recreate my issue I'm having in a real app. I'm my real app the `[disabled]` property is always false but I see the `ng-reflect-disabled` attribute updating to `true | false`

**This is what I have to do in my real app test**
```
function expectSignButtonDisabled(find: any, disabled: boolean) {
    const signButton = find('#sign-button');
    // signButton.nativeElement.disabled always returns false ???
    expect(signButton.attributes['ng-reflect-disabled'] === `${disabled}`).toBe(disabled);
  }
```

In my stackblitz app it doesn't appear to be responding to my `click()` which seems odd but I even tried hardcoding `[disabled]` to be `true | false`.

**Why does `.nativeElement.disabled` always returning false? I assume I'm missing something...**

https://stackblitz.com/edit/shallow-render-r8qh8d?file=examples%2Fcomponent-with-template-var.spec.ts

```
import { Component, NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms'
import { Shallow } from 'shallow-render';

////// Module Setup //////
interface Person {
  firstName: string;
  lastName: string;
  birthDate: Date;
}

@Component({
  selector: 'my-comp',
  template: `
    <input type="checkbox" id="cbox" name="cbox" #cbox [(ngModel)]="cbox.selected">
    <button id="btn" [disabled]="!cbox.selected" [innerText]="cbox.selected? 'Submit': 'Disabled'">Submit</button>
  `,
})
class MyComponent {
}

@NgModule({
  imports: [FormsModule],
  declarations: [MyComponent]
})
class MyModule {}
//////////////////////////

describe('component with bindings', () => {
  let shallow: Shallow<MyComponent>;

  beforeEach(() => {
    shallow = new Shallow(MyComponent, MyModule);
  });


  it('button should be disabled, text should say Disabled', async () => {
    const {find, fixture} = await shallow.render(
      '<my-comp></my-comp>'
    );

    let btn = find('#btn');
    let checkbox = find ('#cbox');

    expect(btn.nativeElement.disabled).toBe(true);
    expect(btn.nativeElement.innerText).toBe('Disabled');
  });

  it('button should be enabled, text should say Submit', async () => {
    const {find, fixture} = await shallow.render(
      '<my-comp></my-comp>'
    );

    let checkbox = find('#cbox');
    let btn = find('#btn');

    checkbox.nativeElement.click();
    
    expect(btn.nativeElement.innerText).toBe('Submit');
    expect(btn.nativeElement.disabled).toBeFalsy();
  });
});

```

**Comment by getsaf** [comment]
Hey, thanks for the issue. The StackBlitz was very helpful... Here's what I found:

The component uses `cbox.selected` but I *think* you intended to use `cbox.checked`.

One final issue is that in your tests, when you trigger an event that alters the DOM (the click in this instance), you must fire a `fixture.detectChanges()` to re-render the DOM and see your changes.

After applying those two changes, your test passed!

I've made these changes in a fork of your StackBlitz [here](https://stackblitz.com/edit/shallow-render-abxc6j?file=examples/component-with-template-var.spec.ts).

**Comment by ticklemycode** [comment]
Hmmm, yeah I was trying a few things but it looks like I was missing the `fixture.detectChanges()` in this example. Feel like I tried this in my app test but this at least proves `.nativeElement.disabled` should return `true` or `false`. I'll poke at it some more!

Thanks for you help and quick reply! **shallow-render is fantastic!**
