### ISSUE TITLE
ModuleWithProviders is not generic error

### ISSUE THREAD

**Issue by ianmediamiser** [getsaf/shallow-render#70]
I have an Angular 5-based module (5.2 to be precise) and when I use the latest version (6.2.0) I get the following error message during the test run:

```
$ yarn test
yarn run v1.7.0
$ ng test
 10% building modules 1/1 modules 0 active16 10 2018 13:38:59.629:WARN [karma]: No captured browser, open http://localhost:9876/
16 10 2018 13:38:59.643:INFO [karma]: Karma v3.0.0 server started at http://0.0.0.0:9876/
16 10 2018 13:38:59.645:INFO [launcher]: Launching browser ChromeHeadless with unlimited concurrency
16 10 2018 13:38:59.651:INFO [launcher]: Starting browser ChromeHeadless
[./src/polyfills.ts] ./src/polyfills.ts 0 bytes {polyfills} [built]
   [0] multi ./src/polyfills.ts 28 bytes {polyfills} [built]
[./src/test.ts] ./src/test.ts 0 bytes {main} [built]


ERROR in node_modules/shallow-render/dist/lib/models/test-setup.d.ts(9,50): error TS2315: Type 'ModuleWithProviders' is not generic.
node_modules/shallow-render/dist/lib/models/test-setup.d.ts(9,88): error TS2315: Type 'ModuleWithProviders' is not generic.
```

If I edit the test-setup.d.ts file at line 9 and change it (removing the `<any>` following `ModuleWithProviders`):

`readonly moduleReplacements: Map<Type<any> | ModuleWithProviders, Type<any> | ModuleWithProviders>;`

compilation now completes. I tried stepping back to v6.1.3 but the error still occurred. 

Is there a version I could use so that I didn't have to manually edit the file (worried about deploying this to my co-workers so they can start writing tests using the shallow-render package). 

I'm just forging into the world of testing frontend code involving Angular. Happy to provide additional info if I haven't provide sufficient details. Trying to get testing to work first then consider migrations to Angular 6 and beyond if possible.

**Comment by getsaf** [comment]
Ahh, looks like [Angular changed `ModuleWithProviders`](https://github.com/angular/angular/commit/60aeee7abfcc149d9f33ed9519b242b4bccea641#diff-968ca8dead1eca4223cb534b9f0b9c02R79) recently to be a generic. My releases are built off of Angular 6x and the Ng6 types are copied out into my d.ts files. I'll have to make my own custom type to make sure I'm still compatible with the older versions of Angular.

Thanks for the issue. I'll have a fix out soon! In the mean-time you may have to go back to 6.1.x until I cut the next release.

**Comment by getsaf** [comment]
Give [6.2.1](https://github.com/getsaf/shallow-render/releases/tag/v6.2.1) a try and let me know if that works!

**Comment by ianmediamiser** [comment]
The 6.2.1 version worked. Thanks.

**Comment by jayna456** [comment]
@getsaf , need to change @angular/core version to 6.2.1?

**Comment by getsaf** [comment]
The 6.2.1 version in the comments above were referencing shallow-render 6.2.1 but that was a while back. If you're on Angular 5x, I'd recommend going with the last of the 7x releases (which was the last major that supported Angular 5).

`npm i -D shallow-render@7`

**Comment by Pinka30** [comment]
I am getting same error. Using Angular 6.
I tried what @getsaf said, but still getting below error

`
ERROR in node_modules/@angular/platform-browser/src/browser.d.ts(45,9): error TS2315: Type 'ModuleWithProviders' is not generic.
node_modules/@angular/router/src/router_module.d.ts(101,60): error TS2315: Type 'ModuleWithProviders' is not generic.
node_modules/@angular/router/src/router_module.d.ts(105,38): error TS2315: Type 'ModuleWithProviders' is not generic.`

Please help.

**Comment by getsaf** [comment]
Which version(s) of Angular/shallow-rendera are you using?

what is the output of:
```
npm ls shallow-render @angular/core
```

**Comment by Pinka30** [comment]
I guess it was not there earlier, on your suggestion I installed it yesterday.
Above command is giving below output,

`PS D:\cakewale> npm ls shallow-render @angular/core
cakewale@0.0.0 D:\cakewale
+-- UNMET PEER DEPENDENCY @angular/core@6.0.3 
`-- shallow-render@7.2.0
` 
below is my package.json for your reference,

`"dependencies": {
    "@angular/animations": "^6.0.0",
    "@angular/cdk": "^6.0.0",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "6.0.3",
    "@angular/forms": "6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "animate.css": "^3.7.2",
    "core-js": "^2.5.4",
    "rxjs": "6.0.0",
    "wowjs": "^1.1.3",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.8",
    "@angular/cli": "~6.0.8",
    "@angular/compiler-cli": "^6.0.3",
    "@angular/language-service": "^6.0.3",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "shallow-render": "^7.2.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }`

**Comment by getsaf** [comment]
I don't think this is a shallow-render issue. In the error stack you posted the error is coming from `@angular/router` and `@angular/platform-browser`. My guess is that somehow your angular libraries are on mis-matched versions.

I would try running:
`npm ls @angular/core @angular/router @angular/platform-browser`

and make sure they all match up to be the same versions.

For sanity, I just created an Angular 6.1 project and installed shallow-render@7 and everything worked fine.
Here's my project for reference: https://github.com/getsaf/ng6-shallow-render

**Comment by Pinka30** [comment]
Thanks a lot. You spotted the exact issue. `@angular/core` had version without ^ sign and other two did not. I removed ^ from other two and did `npm i`. It's working. :)

**Comment by sagar-beep** [comment]
i am using angular 6.1.5 but i am getting this error
ERROR in node_modules/ngx-device-detector/lib/device-detector.module.d.ts(3,23): error TS2315: Type 'ModuleWithProviders' is not generic.

**Comment by getsaf** [comment]
> ModuleWithProviders

Which version of shallow-render are you using? You should be on a version of shallow-render no later than v8x for use with Angular 6.

**Comment by sagar-beep** [comment]
Thank you 😊
