### ISSUE TITLE
Angular Material Failed: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by mihalcan** [getsaf/shallow-render#74]
I just want to share the fix to the problem that I've recently encountered when using Angular Material:

> Failed: Cannot read property 'indexOf' of undefined
>         
>TypeError: Cannot read property 'indexOf' of undefined
>             at HammerGesturesPlugin.push../node_modules/@angular/platform-browser/fesm5/platform-browser.js.HammerGesturesPlugin.isCustomEvent (http://localhost:9876/node_modules/@angular/platform-browser/fesm5/platform-browser.js?:1585:74)
>
>    // Remaining of the stack trace....

The error appears when adding one of the modules: **MatSliderModule, MatSlideToggleModule or MatTooltipModule**

To fix the problem add `Shallow.neverMock(HAMMER_GESTURE_CONFIG);` to your tests or better to append it to the end of the _test.ts_ file.

Explanation:
Aforementioned modules have the following provider declared as part of the module declaration
`{provide: HAMMER_GESTURE_CONFIG, useClass: GestureConfig}`
As **shallow-render** mock the implementation, test execution fails. Adding `Shallow.neverMock` prevents the error.

**Comment by kylecannon** [comment]
@getsaf can we consider never mocking in the library without having us to declare it?

**Comment by getsaf** [comment]
I'm not sure how to reliably auto-mock and I'm also not sure everyone would always want to mock. Also not sure I want to maintain a list of 3rd party libraries and keep up with what should/shouldn't be mocked in all of them.

Fortunately, it only takes one line per-project to skip mocking globally (assuming you use `neverMock` in your global test-setup.
