### ISSUE TITLE
How to return different values for multiple calls on a mock method

### ISSUE THREAD

**Issue by sshabdali** [getsaf/shallow-render#75]
How can I achieve following using shallow-render mocking approach.

spyOn(util, "foo").and.returnValues(true, false); 

expect(util.foo()).toBeTruthy();
expect(util.foo()).toBeFalsy();

**Comment by getsaf** [comment]
Shallow uses `Jasmine` spys/mocks so you may still do more complex mocking like this in your tests (similar to how you would with `TestBed`).

```typescript
const {get} = await shallow.render();
const util = get(UtilClass); // This is similar to `TestBed#get` but the return value is type-safe.
spyOn(util, 'foo').and.returnValues(true, false);
...
```

Really any mocking library should work though. I often use (`ts-mockery`)[https://www.npmjs.com/package/ts-mockery] as a more type-safe alternative to `Jasmine`.

**Comment by Nxt3** [comment]
This doesn't seem to work. If you do this, you still get the error "UtilClass has already been spied upon"

**Comment by getsaf** [comment]
@Nxt3 In this scenario, you will need to work with the existing spy with a cast like so:

```ts
// Assuming you have already provided a mock or have otherwise already spied on the foo function
const {get} = await shallow.mock(UtilClass, {foo: () => true}).render();

// At this point, the foo function is already a spy and will need to be re-cast to make alterations.
(get(UtilClass).foo as jasmine.Spy).and.returnValues(true, false); 
```

**Comment by Nxt3** [comment]
Nice! Thanks for the help--that worked a treat. 😀
