### ISSUE TITLE
TypeError: Cannot read property 'injector' of null

### ISSUE THREAD

**Issue by mibto** [getsaf/shallow-render#85]
Hi there

i'm struggling to setup shallow-render in my meteor angular project. Hopefully you can help me.

I'm getting following error:

     TypeError: Cannot read property 'injector' of null
     at TestBedViewEngine._createCompilerAndModule (packages/modules.js?hash=9bf6a4a74870f7e24c465ccdd26da1c74b199b4c:42029:49)
     at TestBedViewEngine.compileComponents (packages/modules.js?hash=9bf6a4a74870f7e24c465ccdd26da1c74b199b4c:41942:35)
     at Function.TestBedViewEngine.compileComponents (packages/modules.js?hash=9bf6a4a74870f7e24c465ccdd26da1c74b199b4c:41802:81)
     at Renderer.\u003Canonymous> (packages/modules.js?hash=9bf6a4a74870f7e24c465ccdd26da1c74b199b4c:2680:16)
     at step (packages/modules.js?hash=9bf6a4a74870f7e24c465ccdd26da1c74b199b4c:2538:19)
     at Object.next (packages/modules.js?hash=9bf6a4a74870f7e24c465ccdd26da1c74b199b4c:2468:14)
     at packages/modules.js?hash=9bf6a4a74870f7e24c465ccdd26da1c74b199b4c:2440:67
     at new Promise (\u003Canonymous>)
     at __awaiter (packages/modules.js?hash=9bf6a4a74870f7e24c465ccdd26da1c74b199b4c:2417:10)
     at Renderer.render (packages/modules.js?hash=9bf6a4a74870f7e24c465ccdd26da1c74b199b4c:2644:12)`

i have following packages installed:

     "devDependencies": {
          "chai": "^4.2.0",
          "chromedriver": "^2.41.0",
          "faker": "^4.1.0",
          "shallow-render": "^7.1.2",
          "selenium-webdriver": "^3.6.0",
          "sinon": "^7.2.3"
     },

and in packages:
*  jquery
*  sanjo:jasmine

And following Code:

     import { AppModule } from '../../app.module';`

     import { ServersFormComponent } from "../servers-form.component";`

     import { Shallow } from 'shallow-render';`

     describe("ServersFormComponent", () => { 
          let shallow: Shallow<ServersFormComponent>;
          beforeEach(()=>{
               shallow = new Shallow(ServersFormComponent, AppModule);
          });

          it('should render this', async () => {
               const {find} = await shallow.render('<servers-form></servers-form>');
               console.log(find("h5"));
          });
     });

I run the tests with:

    TEST_BROWSER_DRIVER=chrome meteor test --once --driver-package meteortesting:mocha

**Comment by getsaf** [comment]
Hey, thanks for the detail in your post. I don't see anything wrong with your setup , are there any third-party Angular modules you are using in your app? Sometimes third-party modules (like HammerJS) do weird things that prevent them from being mockable.

If you have any of these modules, you may need to use `dontMock` or `neverMock` so your tests use the real-thing, or provide some sort of setup-object to satisfy those libraries.

Can you provide your module setup?

**Comment by mibto** [comment]
Hey :)
Many thanks for your response! i'm some steps further. i found out, that i have to initialize TestBed first.

    import { BrowserDynamicTestingModule, platformBrowserDynamicTesting} from '@angular/platform-browser-dynamic/testing';
    import { TestBed } from "@angular/core/testing";

    beforeEach(()=>{
        TestBed.initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting());

that gave me following error:

    Can't resolve all parameters for ApplicationModule: (?)

which i could solve with:

    import "angular2-meteor-polyfills";

currently i'm stuck with:

    constructor( private route: ActivatedRoute ){
        this.paramsSubscription = this.route.params.subscribe((params: any) => {});
    }

this.route.params is null. i guess i have to exclude ActivatedRoute from getting mocked.
Thanks alot for your help!

**Comment by getsaf** [comment]
Hey @mibto, noticed that your troubles are with the Router. The Angular router has a prescribed testing methodology. I have an example of how to test with the router in the examples [here](https://stackblitz.com/github/getsaf/shallow-render-stackblitz?file=examples%2Fcomponent-with-routing.spec.ts)

You must use Angular's `RouterTestingModule` in your test like so:
```typescript
    shallow = new Shallow(GoHomeLinkComponent, GoHomeModule)
      .replaceModule(RouterModule, RouterTestingModule.withRoutes(routes));
```

Hope this helps!
