### ISSUE TITLE
Incompatiblity with hammerjs components

### ISSUE THREAD

**Issue by checketts** [getsaf/shallow-render#86]
I haven't gotten to the root of this one, but my normal Angular tests are passing fine, but those that leverage `shallow-render` are failing now that I have added some material components that support hammerjs.

See https://material.angular.io/guide/getting-started#step-5-gesture-support

When running in the browser, the console merely states that hammerjs is needed to support some gestures. I haven't added hammerjs to the project yet.

Instead of seeing the warning in my tests, I see 

```
TypeError: Cannot read property 'indexOf' of undefined

      at HammerGesturesPlugin.isCustomEvent (../packages/platform-browser/src/dom/events/hammer_gestures.ts:236:74)
      at HammerGesturesPlugin.supports (../packages/platform-browser/src/dom/events/hammer_gestures.ts:163:71)
      at EventManager._findPluginFor (../packages/platform-browser/src/dom/events/event_manager.ts:83:18)
      at EventManager.addEventListener (../packages/platform-browser/src/dom/events/event_manager.ts:50:25)
      at DefaultDomRenderer2.listen (../packages/platform-browser/src/dom/dom_renderer.ts:218:42)
      at BaseAnimationRenderer.listen (../../packages/platform-browser/animations/src/animation_renderer.ts:194:26)
```

So it appears that some hammer placeholder module is being mocked when it shouldn't be.

**Comment by getsaf** [comment]
Aww man, I remember Hammer being weird in some tests on another project I worked on. Are you using the `NoopAnimationsModule`?

Last project I  worked on that used Animations, we did it globally with something like this so all the Shallow tests automatically hooked up the test module:

```typescript
Shallow
  .alwaysReplaceModule(BrowserAnimationsModule, NoopAnimationsModule)
  .neverMock(NoopAnimationsModule);
```

I vaguely remember someone needing to either provide a HAMMER_GESTURE_CONFIG or neverMock that too.

If those don't work out for you, maybe we can reproduce it in a StackBlitz and collaborate on it there.

**Comment by kreatemore** [comment]
I can't yet give you a reproducible example, but I can confirm that `shallow(...).dontMock(HAMMER_GESTURE_CONFIG)` did work for us.

**Comment by getsaf** [comment]
Thank you for the update!

**Comment by kreatemore** [comment]
I've spent a few hours on this already, and can't seem to reproduce the problem in a new project, (even when I try to replicate the behaviour of the components that originally raised this issue). I'll try to dig deeper, although I'm wondering if a mention of the error (and the solution you suggested above) would be sufficient in the docs, since this doesn't seem to be affecting many users?

**Comment by getsaf** [comment]
@kreatemore Good idea, you're not the first one to ask for something like this:
https://github.com/getsaf/shallow-render/wiki/FAQ

**Comment by kreatemore** [comment]
Ninja update: I could create a reproducible example, the problem seems to be using both something that needs Hammerjs and adding callbacks to be executed on event emissions, like: https://github.com/kreatemore/shallow-render-hammerjs/blob/master/src/app/input/input.component.html
