### ISSUE TITLE
Adding jest support

### ISSUE THREAD

**Issue by kylecannon** [getsaf/shallow-render#99]
I did see that in  #76 that you were thinking about adding Jest support. Is this something that is on the roadmap?

**Comment by kreatemore** [comment]
👋🏼 I’m using jest with shallow-render on multiple projects (both personal and work related) and it works perfectly fine. Is there anything specific you need help with?

**Comment by kylecannon** [comment]
It seems to be related to when I use the `.mock` methods. I have it working in some instances where I don't have to mock anything. However, if you look at the code base, you'll see that jasmine is used in some parts of the codebase https://github.com/getsaf/shallow-render/search?utf8=%E2%9C%93&q=jasmine&type=

This is also an issue: https://github.com/getsaf/shallow-render/blob/a30d987633530c442ef6480e7985599094826747/lib/models/mock-of-provider.ts

**Comment by getsaf** [comment]
Yeah, so I hadn't used Jest for Angular tests before but I have been using it more in other projects. I just learned that Jest ships with a "monkeypatched" version of Jasmine which means Jasmine spys work with Jest out-of-the-box.

I think this means that Shallow already supports Jest because it uses Jest-compatible Jasmine spys (as @kylecannon pointed out).

@kreatemore, It seems that there's no work to do on this one unless you have experienced any quirks on your end.

**Comment by kylecannon** [comment]
I tried running Jest today on a project that was using .mock and it was failing using jest. 

```
 TypeError: jasmine.isSpy is not a function

      32 | 
      33 |     it('renders', async () => {
    > 34 |         const { element } = await shallow.render('<app-dashboards-page></app-dashboards-pag
e>');
         |                                           ^
      35 |         expect(element).toBeTruthy();
      36 |     });
      37 | });

      at ../../node_modules/shallow-render/lib/models/mock-of-provider.ts:7:73
          at Array.forEach (<anonymous>)
      at MockProvider.MockOfProvider (../../node_modules/shallow-render/lib/models/mock-of-provider.ts
:6:24)
```

Some jasmine methods work out of the box but not all.

**Comment by kreatemore** [comment]
Seems right, this reproduces the above: https://github.com/kreatemore/shallow-render-hammerjs/blob/master/src/app/app.component.spec.ts#L9

I've found similar code on another project (with more dependencies, like `jest-preset-angular`), maybe there it's a case of another package fixing this.

**Comment by kreatemore** [comment]
@getsaf I'm going to have quite a busy weekend in front of me, but would you mind if I'd give this a go?

**Comment by getsaf** [comment]
Please do. I wonder if if we could auto-detect if jest or Jasmine are
available and use the whichever one we find.!

**Comment by kylecannon** [comment]
ts-mockery handles this nicely. Taking a look at it might not be a bad idea.

**Comment by getsaf** [comment]
Also would be preferable to avoid pulling in additional packages if we can
